### ISSUE TITLE
User controlled data in methods like `innerHTML`, `outerHTML` or `document.write` is an anti-pattern that can lead to XSS vulnerabilities

### ISSUE THREAD

**Issue by copyleftdev** [SharokhAtaie/extractify-extension#1]
https://github.com/SharokhAtaie/extractify-extension/blob/ef7a9121ab2556703469515b48ce76d4d76f28bc/animation.js#L48C1-L48C37

**Comment by SharokhAtaie** [comment]
It's just a chrome extension
